Feature/25 accommodation get all
VentionCapstone/Backend pull request #15
Opened 2023-12-08 18:59 UTC by Zach13131

add get all accommodations endpoint, fix error handling in auth login func

2023-12-11 03:41 UTC, mirsadikov approved these changes

2023-12-11 10:38 UTC, gitkoshelew requested changes

2023-12-11 10:55 UTC, mirsadikov commented on src/main.ts
> +    origin: process.env.ANY_ORIGIN === 'true' ? true : process.env.FRONTEND_URL,
@gitkoshelew so it can stay like this for now?

2023-12-11 11:36 UTC, Zach13131 commented on src/filters/global.filter.ts
> +        error: { statusCode: errorObj.statusCode, message: errorObj.message },
yes i chenged

2023-12-11 12:26 UTC, Zach13131 commented on src/auth/auth.service.ts
> +      sameSite: this.config.get('COOKIE_SAME_SITE') as 'strict' | 'lax' | 'none' | undefined,
yes, my bad, i created this branch from another branch, not from develop and therewhy there i have changes from that branch included to my.

2023-12-15 09:04 UTC, gitkoshelew approved these changes

2023-12-15 09:06 UTC, merged