Fix/70 endpoints
VentionCapstone/Backend pull request #22
Opened 2023-12-16 10:39 UTC by safyurtago

Fix all endpoints as more code quality
Fix swagger documentation

2023-12-16 13:28 UTC, Zach13131 requested changes

2023-12-16 13:28 UTC, Zach13131 commented on src/auth/auth.controller.ts
> +  })
You are not supposed to do this, instead need to provide a schema. 

Here is the example. 

```js
  @ApiOperation({ summary: 'Sign up user' })
  @ApiResponse({
    status: 201,
    description: 'User created succesfully',
    schema: {
      properties: {
        success: { type: 'boolean' },
        message: {
          type: 'string',
        },
      },
    },
  })
```

2023-12-16 13:28 UTC, Zach13131 commented on src/auth/auth.controller.ts
>    @ApiBearerAuth()
You shouldn't write a request word. 
```js
@ApiOperation({ summary: 'Update email' })
```

2023-12-16 13:28 UTC, Zach13131 commented on src/user/user.controller.ts
>    @ApiParam({ name: 'id', description: 'User profile ID' })
Write this and one above summary in lowercase.

2023-12-16 13:28 UTC, Zach13131 commented on src/auth/auth.controller.ts
1.  If you decide to return an object with a 'success' field, please apply this to all your responses.
2.  Create schemas instead of strings.

2023-12-16 13:28 UTC, Zach13131 commented on src/accommodation/accommodation.controller.ts
You missed fixing the summary in line 254:
```js 
@ApiOperation({ summary: 'GET ALL YOUR ACCOMMODATIONS' })
```

2023-12-17 16:11 UTC, Zach13131 requested changes

2023-12-17 16:54 UTC, Zach13131 approved these changes
Good job!

2023-12-18 08:25 UTC, gitkoshelew commented on src/accommodation/accommodation.controller.ts
> -  @Post('/file/:id')
could you rename the endpoint. 'file' is to generic name. better rename it to preview-upload or smth like that. There is  possible other files.

2023-12-24 11:33 UTC, mirsadikov approved these changes

2023-12-26 07:10 UTC, gitkoshelew approved these changes

2023-12-26 08:12 UTC, merged