Feature/25 accommodation api
VentionCapstone/Backend pull request #4
Opened 2023-12-03 18:49 UTC by Zach13131

Add accommodation module and fix swagger

2023-12-04 10:56 UTC, mirsadikov approved these changes

2023-12-04 11:50 UTC, gitkoshelew requested changes

2023-12-04 11:50 UTC, gitkoshelew commented on src/accommodation/accommodation.service.ts
> +      throw new Error('You not owner of this accommodation');
please use nestJs Exceptions or create custom if there is no needed exception

2023-12-04 11:50 UTC, gitkoshelew commented on src/accommodation/accommodation.service.ts
> +    const newAccommodation = await this.prisma.accommodation.create({
you should wrap all awaits to try catch block, because there are possible unexpected exceptions

2023-12-05 08:38 UTC, gitkoshelew approved these changes

2023-12-05 08:38 UTC, merged